config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :slack_response, only: [:create]
  resources :tags, only: [:show]
  resources :search, only: [:index]

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  has_many :slack_responses

  searchable do
    text :title, :content, :hash_tags
  end
end

app/models/slack_conversation.rb
class SlackConversation < ActiveRecord::Base
  has_many :slack_responses

  def incomplete?
    !complete?
  end

end

app/models/slack_response.rb
class SlackResponse < ActiveRecord::Base
  belongs_to :slack_conversation
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = BlogPost.all
    respond_to do |format|
      format.html
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search = BlogPost.search { fulltext "#{params[:search]}*" }
    @posts = search.results
  end
end

app/controllers/slack_response_controller.rb
class SlackResponseController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    puts params

    SlackResponseSaver.new( params ).save

    render nothing: true
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :hash_tag

  def show
    @posts = QueryHashTags.new(hash_tag, BlogPost).find
  end

  private
    def hash_tag
      "##{params[:id]}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/post_helper.rb
module PostHelper

  def posted_on posted_at
    posted_at.strftime("%B %e, %Y")
  end

  def post_tags tags
    tags.map do |tag|
      link_to tag, tag_path( tag.delete('#') )
    end.join(", ").html_safe
  end
end

app/views/application/_posts.html.slim
/! Main Content
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      - @posts.each do |post|
        .post-preview

          a href="#"
            h2.post-title= post.title

          - if post.slack_responses.any?
            = render "responses", responses: post.slack_responses
          - else
            p= post.content

          p.post-meta
            ' Posted
            / a href="#"  Start Bootstrap
            | on #{posted_on(post.created_at)}

          - if post.hash_tags.any?
            p.tags
              i.glyphicon.glyphicon-tags>
              = post_tags( post.hash_tags )

        hr

app/views/application/_responses.html.slim
ul.responses
  - responses.each do |response|
    li
      .response-author
        strong = response.user_name
      .response-text
        = response.text

app/views/application/_search.html.slim
.container
  .row
    .col-md-6.col-md-offset-6
      = form_tag(search_index_path, method: 'GET') do
        .input-group
          = text_field_tag :search, params[:search], class: 'form-control input-lg', placeholder: 'Search...'
          span.input-group-btn
            button.btn.btn-default Search!

app/views/home/index.html.slim
= render 'posts'

app/views/layouts/_footer.html.slim
hr
  /! Footer
  footer
    .container
      .row
        .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
          ul.list-inline.text-center
            li
              a href="#"
                span.fa-stack.fa-lg
                  i.fa.fa-circle.fa-stack-2x
                  i.fa.fa-twitter.fa-stack-1x.fa-inverse
            li
              a href="#"
                span.fa-stack.fa-lg
                  i.fa.fa-circle.fa-stack-2x
                  i.fa.fa-facebook.fa-stack-1x.fa-inverse
            li
              a href="#"
                span.fa-stack.fa-lg
                  i.fa.fa-circle.fa-stack-2x
                  i.fa.fa-github.fa-stack-1x.fa-inverse
          p.copyright.text-muted Copyright &copy; Your Website 2014

app/views/layouts/_header.html.slim
ruby:
  image ||= nil
  subheading ||= nil
  if image
    props = {style: "background-image: url('#{image_path(image)}')" }
  else
    props = {}
  end

header.intro-header*props
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .site-heading
          h1 = title
          - if subheading
            hr.small
              span.subheading = subheading

app/views/layouts/_navigation.html.slim
/! Navigation
nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header.page-scroll
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href=(root_path) Eavesdropper
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          a href=root_path  Home

app/views/layouts/application.html.slim
doctype html
html
head
  title Knowledge Base
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
body

  = render 'layouts/navigation'
  = yield
  = render 'layouts/footer'

app/views/search/index.html.slim
= render 'layouts/header', image: 'home-bg.jpg', title: "Eavesdropper", subheading: "We are watching you!"
= render 'search'
= render 'posts'

app/views/tags/show.html.slim
= render 'layouts/header', image: 'home-bg.jpg', title: "Eavesdropper", subheading: "We are watching you!"

= render 'posts'